url: https://github.com/alemorcuq/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.36
commit: 7e98ef1d41cf5913483638c67ec2ade09d910ef0
version: 106.1.8-rc.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/alemorcuq/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.36
      commit: 7e98ef1d41cf5913483638c67ec2ade09d910ef0
doNotRelease: false
